### ISSUE TITLE
Restoring from backup

### ISSUE THREAD

**Issue by ryvin** [toshke/big-blue-button-cloudformation-cfhl#12]
I'm looking to shutdown and restart a cloudformation stack later when needed, without losing saved data and users. I'm not sure what process and consideration should be followed for restoring from backup, sorry if I miss something basic, I'm still learning. :)

I can launch the stack using the last snapshot AMI and it works if the running stack is not offline for too long. If the system is offline and you get a different EIP when the new stack is launched from an AMI snapshot everything comes up and is available, but a client connecting to this new stack can't start audio (video is fine) and gets an "Error 1002: Could not make a websocket connection" error when trying to enable audio.  

I'm guessing there are files that need to be updated with new external and internal IPs when the new stack is launched from what I can tell. Could adjusting the IP values in the files when the stack is launched to the current EIP/internal IP allow new deployments and deployments from backups to work?

**Comment by toshke** [comment]
@ryvin  I'm working on deploying the server as standalone EC2 Instance, rather than ASG (AutoScalingGroup). This will allow you to stop the server, and start it when you need, without the need to tear the whole stack down. 

As for the IPs, you just may be right that some configuration files retain old ip configuration value. With that said, it is possible to reuse EIP created outside of the CloudFormation, if you generate your own templates and change `external_eip` to `true` here - https://github.com/toshke/big-blue-button-cloudformation-cfhl/blob/master/bbb.config.yaml#L19. Please read through **Configuration** section of README.md on how to build and publish your own templates.  Once `external_eip` is set to true, you should get new cfn parameter `ElasticIP`, and reuse existing one. 

I will keep you posted around the EC2 start/stop feature, as it much convenient as cost savings measure without rebuild the stack/or losing any data.

**Comment by ryvin** [comment]
I like the ASG, is it possible to set the autoscaling group to desired number of servers to 0, then change back to 1 when you want to start up the service again without losing the data?

I'll look at building and publishing my own template and try the external_eip you mention.

**Comment by toshke** [comment]
@ryvin not really without data loss, unless you have created an AMI from your instance - it's not possible to set ASG size to 0. An EC2 module that is in works should fix this up, as you would be allowed to start/stop the instance itself as deemed appropriate.

**Comment by toshke** [comment]
@ryvin  on rolling the solution out as EC2 only w/ASG - https://github.com/toshke/big-blue-button-cloudformation-cfhl/pull/13. I would say that you can scale this horizontally for a long time before vertical scaling is required, given the broad range of instance types available from amazon.

**Comment by toshke** [comment]
@ryvin https://github.com/toshke/big-blue-button-cloudformation-cfhl/pull/13 has been merged, and new templates include `EC2` as deployment option. With `EC2` you can start/stop instance as cost savings measure as you deem appropriate.
