### ISSUE TITLE
Cant get Authentications with Script

### ISSUE THREAD

**Issue by ElCativoGER** [toshke/big-blue-button-cloudformation-cfhl#16]
Hi Nikola.

Thank you for your kind help with routing.
Now I try to get my Auth Data with yout Script.
As I am just a Windows User, I am not familiar with the Bash.
I use the SSM Connect Button in Instances Screen of AWS to Connect to my BBB Instance.
No i copy your Script into the Bash and hit Enter.
_instance_id=$(aws ec2 describe-instances --filters \
     "Name=instance-state-name,Values=running" \
     "Name=tag:Name,Values=BigBlueButton-Server" \
     --query 'Reservations[].Instances[].InstanceId' --output text)_

Now it comes up with:
_An error occurred (UnauthorizedOperation) when calling the DescribeInstances operation: You are not authorized to perform this operation..._

Same with Default admin credentials.
After starting script in my Bash it comes up with:
_An error occurred (AccessDeniedException) when calling the GetParameter operation..._

This happen on every Script.
Seems I am doing something wrong.
Can anyone help?

Greeting
Alex

**Comment by ElCativoGER** [comment]
How can I setup my credentials for this to run?
Remember, i am using Windows.

**Comment by toshke** [comment]
@ElCativoGER  
this is permissions problem with IAM user/role you are using. You can check which user is your local profile configured with by running `aws sts get-caller-identity`. For this particular example you'll need following api permissions attached to your user

- `ssm:GetParameter` 
- `ec2:DescribeInstances` 
- `ssm:StartSession`
- `ssm:StopSession`
- `kms:Decrypt`

(I may have missed something here)

[Read here on attaching policies to your IAM users](https://docs.aws.amazon.com/IAM/latest/UserGuide/id_users_change-permissions.html)

As this issue relates to your local permissions, rather than the bbb solutions, I think issue could be closed - though leaving it open for now to update the doco for required permissions.

**Comment by toshke** [comment]
@ElCativoGER  closing this one, as it is not solution related, but rather local permissions.
